name: fide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^6.0.0
  web_socket_channel: ^3.0.3
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.8
  archive: ^4.0.7
  path_provider: ^2.1.5
  flutter_inappwebview: ^6.1.5
  process_run: ^1.2.4
  flutter_highlight: ^0.7.0
  font_awesome_flutter: ^10.8.0
  code_forge: ^4.3.0
  path: ^1.9.1
  google_fonts: ^7.0.2
  re_highlight: ^0.0.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/scripts/

  fonts:
    - family: NeoFolia
      fonts:
        - asset: assets/fonts/neofolia.otf